title: MadTinker
description: ""
url: "https://ndangelo.github.io/madtinker"

baseurl: "https://ndangelo.github.io/madtinker" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
theme: minima

# Exclude files from production
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor