url: "https://ndangelo.github.io"
baseurl: "/madtinker"


description: The Mad Tinker

permalink: /:categories/:year/:month/:day/:title/
paginate: 1


         
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
highlighter: rouge
baseurl: /

