backend:
  name: test-repo

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true

    fields:
      - { label: "Title", name: "title", widget: "string" }

      - { label: "Body", name: "body", widget: "markdown" }